networks:
  subnet: {}

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - subnet

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - subnet
