networks:
  subnet: {}

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - subnet

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - subnet

  minio:
    image: bitnami/minio
    env_file:
      - .data/env.local
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.data/minio:/bitnami/minio/data
